
-- +goose Up
-- SQL in section 'Up' is executed when this migration is applied
ALTER TABLE redirection_pages ADD COLUMN `language` bigint DEFAULT NULL;
ALTER TABLE templates ADD COLUMN `language` bigint DEFAULT NULL;
ALTER TABLE pages ADD COLUMN `language` bigint DEFAULT NULL;
ALTER TABLE languages ADD COLUMN `flag` varchar(25) DEFAULT NULL;

/* Languages */
INSERT INTO `languages` (`name`, `code`) VALUES ('Abkhazian', 'ab');
INSERT INTO `languages` (`name`, `code`) VALUES ('Avestan', 'ae');
INSERT INTO `languages` (`name`, `code`) VALUES ('Afrikaans', 'af');
INSERT INTO `languages` (`name`, `code`) VALUES ('Akan', 'ak');
INSERT INTO `languages` (`name`, `code`) VALUES ('Amharic', 'am');
INSERT INTO `languages` (`name`, `code`) VALUES ('Aragonese', 'an');
INSERT INTO `languages` (`name`, `code`) VALUES ('Arabic', 'ar');
INSERT INTO `languages` (`name`, `code`) VALUES ('Assamese', 'as');
INSERT INTO `languages` (`name`, `code`) VALUES ('Avaric', 'av');
INSERT INTO `languages` (`name`, `code`) VALUES ('Aymara', 'ay');
INSERT INTO `languages` (`name`, `code`) VALUES ('Azerbaijani', 'az');
INSERT INTO `languages` (`name`, `code`) VALUES ('Bashkir', 'ba');
INSERT INTO `languages` (`name`, `code`) VALUES ('Belarusian', 'be');
INSERT INTO `languages` (`name`, `code`) VALUES ('Bulgarian', 'bg');
INSERT INTO `languages` (`name`, `code`) VALUES ('Bihari languages', 'bh');
INSERT INTO `languages` (`name`, `code`) VALUES ('Bislama', 'bi');
INSERT INTO `languages` (`name`, `code`) VALUES ('Bambara', 'bm');
INSERT INTO `languages` (`name`, `code`) VALUES ('Bengali', 'bn');
INSERT INTO `languages` (`name`, `code`) VALUES ('Tibetan', 'bo');
INSERT INTO `languages` (`name`, `code`) VALUES ('Breton', 'br');
INSERT INTO `languages` (`name`, `code`) VALUES ('Bosnian', 'bs');
INSERT INTO `languages` (`name`, `code`) VALUES ('Catalan; Valencian', 'ca');
INSERT INTO `languages` (`name`, `code`) VALUES ('Chechen', 'ce');
INSERT INTO `languages` (`name`, `code`) VALUES ('Chamorro', 'ch');
INSERT INTO `languages` (`name`, `code`) VALUES ('Corsican', 'co');
INSERT INTO `languages` (`name`, `code`) VALUES ('Cree', 'cr');
INSERT INTO `languages` (`name`, `code`) VALUES ('Czech', 'cs');
INSERT INTO `languages` (`name`, `code`) VALUES ('Old Bulgarian', 'cu');
INSERT INTO `languages` (`name`, `code`) VALUES ('Chuvash', 'cv');
INSERT INTO `languages` (`name`, `code`) VALUES ('Welsh', 'cy');
INSERT INTO `languages` (`name`, `code`) VALUES ('Danish', 'da');
INSERT INTO `languages` (`name`, `code`) VALUES ('German', 'de');
INSERT INTO `languages` (`name`, `code`) VALUES ('Divehi; Dhivehi; Maldivian', 'dv');
INSERT INTO `languages` (`name`, `code`) VALUES ('Dzongkha', 'dz');
INSERT INTO `languages` (`name`, `code`) VALUES ('Ewe', 'ee');
INSERT INTO `languages` (`name`, `code`) VALUES ('Greek, Modern (1453-)', 'el');
INSERT INTO `languages` (`name`, `code`) VALUES ('English', 'en');
INSERT INTO `languages` (`name`, `code`) VALUES ('Esperanto', 'eo');
INSERT INTO `languages` (`name`, `code`) VALUES ('Spanish; Castilian', 'es');
INSERT INTO `languages` (`name`, `code`) VALUES ('Estonian', 'et');
INSERT INTO `languages` (`name`, `code`) VALUES ('Basque', 'eu');
INSERT INTO `languages` (`name`, `code`) VALUES ('Persian', 'fa');
INSERT INTO `languages` (`name`, `code`) VALUES ('Fulah', 'ff');
INSERT INTO `languages` (`name`, `code`) VALUES ('Finnish', 'fi');
INSERT INTO `languages` (`name`, `code`) VALUES ('Fijian', 'fj');
INSERT INTO `languages` (`name`, `code`) VALUES ('Faroese', 'fo');
INSERT INTO `languages` (`name`, `code`) VALUES ('French', 'fr');
INSERT INTO `languages` (`name`, `code`) VALUES ('Western Frisian', 'fy');
INSERT INTO `languages` (`name`, `code`) VALUES ('Irish', 'ga');
INSERT INTO `languages` (`name`, `code`) VALUES ('Gaelic; Scottish Gaelic', 'gd');
INSERT INTO `languages` (`name`, `code`) VALUES ('Galician', 'gl');
INSERT INTO `languages` (`name`, `code`) VALUES ('Guarani', 'gn');
INSERT INTO `languages` (`name`, `code`) VALUES ('Gujarati', 'gu');
INSERT INTO `languages` (`name`, `code`) VALUES ('Manx', 'gv');
INSERT INTO `languages` (`name`, `code`) VALUES ('Hausa', 'ha');
INSERT INTO `languages` (`name`, `code`) VALUES ('Hebrew', 'he');
INSERT INTO `languages` (`name`, `code`) VALUES ('Hindi', 'hi');
INSERT INTO `languages` (`name`, `code`) VALUES ('Hiri Motu', 'ho');
INSERT INTO `languages` (`name`, `code`) VALUES ('Croatian', 'hr');
INSERT INTO `languages` (`name`, `code`) VALUES ('Haitian; Haitian Creole', 'ht');
INSERT INTO `languages` (`name`, `code`) VALUES ('Hungarian', 'hu');
INSERT INTO `languages` (`name`, `code`) VALUES ('Armenian', 'hy');
INSERT INTO `languages` (`name`, `code`) VALUES ('Herero', 'hz');
INSERT INTO `languages` (`name`, `code`) VALUES ('Interlingua', 'ia');
INSERT INTO `languages` (`name`, `code`) VALUES ('Indonesian', 'id');
INSERT INTO `languages` (`name`, `code`) VALUES ('Interlingue; Occidental', 'ie');
INSERT INTO `languages` (`name`, `code`) VALUES ('Igbo', 'ig');
INSERT INTO `languages` (`name`, `code`) VALUES ('Sichuan Yi; Nuosu', 'ii');
INSERT INTO `languages` (`name`, `code`) VALUES ('Inupiaq', 'ik');
INSERT INTO `languages` (`name`, `code`) VALUES ('Ido', 'io');
INSERT INTO `languages` (`name`, `code`) VALUES ('Icelandic', 'is');
INSERT INTO `languages` (`name`, `code`) VALUES ('Italian', 'it');
INSERT INTO `languages` (`name`, `code`) VALUES ('Inuktitut', 'iu');
INSERT INTO `languages` (`name`, `code`) VALUES ('Japanese', 'ja');
INSERT INTO `languages` (`name`, `code`) VALUES ('Javanese', 'jv');
INSERT INTO `languages` (`name`, `code`) VALUES ('Georgian', 'ka');
INSERT INTO `languages` (`name`, `code`) VALUES ('Kongo', 'kg');
INSERT INTO `languages` (`name`, `code`) VALUES ('Kikuyu; Gikuyu', 'ki');
INSERT INTO `languages` (`name`, `code`) VALUES ('Kuanyama; Kwanyama', 'kj');
INSERT INTO `languages` (`name`, `code`) VALUES ('Kazakh', 'kk');
INSERT INTO `languages` (`name`, `code`) VALUES ('Kalaallisut; Greenlandic', 'kl');
INSERT INTO `languages` (`name`, `code`) VALUES ('Central Khmer', 'km');
INSERT INTO `languages` (`name`, `code`) VALUES ('Kannada', 'kn');
INSERT INTO `languages` (`name`, `code`) VALUES ('Korean', 'ko');
INSERT INTO `languages` (`name`, `code`) VALUES ('Kanuri', 'kr');
INSERT INTO `languages` (`name`, `code`) VALUES ('Kashmiri', 'ks');
INSERT INTO `languages` (`name`, `code`) VALUES ('Kurdish', 'ku');
INSERT INTO `languages` (`name`, `code`) VALUES ('Komi', 'kv');
INSERT INTO `languages` (`name`, `code`) VALUES ('Cornish', 'kw');
INSERT INTO `languages` (`name`, `code`) VALUES ('Kirghiz; Kyrgyz', 'ky');
INSERT INTO `languages` (`name`, `code`) VALUES ('Latin', 'la');
INSERT INTO `languages` (`name`, `code`) VALUES ('Luxembourgish; Letzeburgesch', 'lb');
INSERT INTO `languages` (`name`, `code`) VALUES ('Ganda', 'lg');
INSERT INTO `languages` (`name`, `code`) VALUES ('Limburgan; Limburger; Limburgish', 'li');
INSERT INTO `languages` (`name`, `code`) VALUES ('Lingala', 'ln');
INSERT INTO `languages` (`name`, `code`) VALUES ('Lao', 'lo');
INSERT INTO `languages` (`name`, `code`) VALUES ('Lithuanian', 'lt');
INSERT INTO `languages` (`name`, `code`) VALUES ('Luba-Katanga', 'lu');
INSERT INTO `languages` (`name`, `code`) VALUES ('Latvian', 'lv');
INSERT INTO `languages` (`name`, `code`) VALUES ('Malagasy', 'mg');
INSERT INTO `languages` (`name`, `code`) VALUES ('Marshallese', 'mh');
INSERT INTO `languages` (`name`, `code`) VALUES ('Maori', 'mi');
INSERT INTO `languages` (`name`, `code`) VALUES ('Macedonian', 'mk');
INSERT INTO `languages` (`name`, `code`) VALUES ('Malayalam', 'ml');
INSERT INTO `languages` (`name`, `code`) VALUES ('Mongolian', 'mn');
INSERT INTO `languages` (`name`, `code`) VALUES ('Marathi', 'mr');
INSERT INTO `languages` (`name`, `code`) VALUES ('Malay', 'ms');
INSERT INTO `languages` (`name`, `code`) VALUES ('Maltese', 'mt');
INSERT INTO `languages` (`name`, `code`) VALUES ('Burmese', 'my');
INSERT INTO `languages` (`name`, `code`) VALUES ('Nauru', 'na');
INSERT INTO `languages` (`name`, `code`) VALUES ('Norwegian Bokmål', 'nb');
INSERT INTO `languages` (`name`, `code`) VALUES ('Ndebele, North; North Ndebele', 'nd');
INSERT INTO `languages` (`name`, `code`) VALUES ('Nepali', 'ne');
INSERT INTO `languages` (`name`, `code`) VALUES ('Ndonga', 'ng');
INSERT INTO `languages` (`name`, `code`) VALUES ('Dutch; Flemish', 'nl');
INSERT INTO `languages` (`name`, `code`) VALUES ('Norwegian Nynorsk', 'nn');
INSERT INTO `languages` (`name`, `code`) VALUES ('Norwegian', 'no');
INSERT INTO `languages` (`name`, `code`) VALUES ('Ndebele, South; South Ndebele', 'nr');
INSERT INTO `languages` (`name`, `code`) VALUES ('Navajo; Navaho', 'nv');
INSERT INTO `languages` (`name`, `code`) VALUES ('Chichewa; Chewa; Nyanja', 'ny');
INSERT INTO `languages` (`name`, `code`) VALUES ('Occitan (post 1500)', 'oc');
INSERT INTO `languages` (`name`, `code`) VALUES ('Ojibwa', 'oj');
INSERT INTO `languages` (`name`, `code`) VALUES ('Oromo', 'om');
INSERT INTO `languages` (`name`, `code`) VALUES ('Oriya', 'or');
INSERT INTO `languages` (`name`, `code`) VALUES ('Ossetian; Ossetic', 'os');
INSERT INTO `languages` (`name`, `code`) VALUES ('Panjabi; Punjabi', 'pa');
INSERT INTO `languages` (`name`, `code`) VALUES ('Pali', 'pi');
INSERT INTO `languages` (`name`, `code`) VALUES ('Polish', 'pl');
INSERT INTO `languages` (`name`, `code`) VALUES ('Pushto; Pashto', 'ps');
INSERT INTO `languages` (`name`, `code`) VALUES ('Portuguese', 'pt');
INSERT INTO `languages` (`name`, `code`) VALUES ('Quechua', 'qu');
INSERT INTO `languages` (`name`, `code`) VALUES ('Romansh', 'rm');
INSERT INTO `languages` (`name`, `code`) VALUES ('Rundi', 'rn');
INSERT INTO `languages` (`name`, `code`) VALUES ('Romanian; Moldavian; Moldovan', 'ro');
INSERT INTO `languages` (`name`, `code`) VALUES ('Russian', 'ru');
INSERT INTO `languages` (`name`, `code`) VALUES ('Kinyarwanda', 'rw');
INSERT INTO `languages` (`name`, `code`) VALUES ('Sanskrit', 'sa');
INSERT INTO `languages` (`name`, `code`) VALUES ('Sardinian', 'sc');
INSERT INTO `languages` (`name`, `code`) VALUES ('Sindhi', 'sd');
INSERT INTO `languages` (`name`, `code`) VALUES ('Northern Sami', 'se');
INSERT INTO `languages` (`name`, `code`) VALUES ('Sango', 'sg');
INSERT INTO `languages` (`name`, `code`) VALUES ('Sinhala; Sinhalese', 'si');
INSERT INTO `languages` (`name`, `code`) VALUES ('Slovak', 'sk');
INSERT INTO `languages` (`name`, `code`) VALUES ('Slovenian', 'sl');
INSERT INTO `languages` (`name`, `code`) VALUES ('Samoan', 'sm');
INSERT INTO `languages` (`name`, `code`) VALUES ('Shona', 'sn');
INSERT INTO `languages` (`name`, `code`) VALUES ('Somali', 'so');
INSERT INTO `languages` (`name`, `code`) VALUES ('Albanian', 'sq');
INSERT INTO `languages` (`name`, `code`) VALUES ('Serbian', 'sr');
INSERT INTO `languages` (`name`, `code`) VALUES ('Swati', 'ss');
INSERT INTO `languages` (`name`, `code`) VALUES ('Sotho, Southern', 'st');
INSERT INTO `languages` (`name`, `code`) VALUES ('Sundanese', 'su');
INSERT INTO `languages` (`name`, `code`) VALUES ('Swedish', 'sv');
INSERT INTO `languages` (`name`, `code`) VALUES ('Swahili', 'sw');
INSERT INTO `languages` (`name`, `code`) VALUES ('Tamil', 'ta');
INSERT INTO `languages` (`name`, `code`) VALUES ('Telugu', 'te');
INSERT INTO `languages` (`name`, `code`) VALUES ('Tajik', 'tg');
INSERT INTO `languages` (`name`, `code`) VALUES ('Thai', 'th');
INSERT INTO `languages` (`name`, `code`) VALUES ('Tigrinya', 'ti');
INSERT INTO `languages` (`name`, `code`) VALUES ('Turkmen', 'tk');
INSERT INTO `languages` (`name`, `code`) VALUES ('Tagalog', 'tl');
INSERT INTO `languages` (`name`, `code`) VALUES ('Tswana', 'tn');
INSERT INTO `languages` (`name`, `code`) VALUES ('Tonga (Tonga Islands)', 'to');
INSERT INTO `languages` (`name`, `code`) VALUES ('Turkish', 'tr');
INSERT INTO `languages` (`name`, `code`) VALUES ('Tsonga', 'ts');
INSERT INTO `languages` (`name`, `code`) VALUES ('Tatar', 'tt');
INSERT INTO `languages` (`name`, `code`) VALUES ('Twi', 'tw');
INSERT INTO `languages` (`name`, `code`) VALUES ('Tahitian', 'ty');
INSERT INTO `languages` (`name`, `code`) VALUES ('Uighur; Uyghur', 'ug');
INSERT INTO `languages` (`name`, `code`) VALUES ('Ukrainian', 'uk');
INSERT INTO `languages` (`name`, `code`) VALUES ('Urdu', 'ur');
INSERT INTO `languages` (`name`, `code`) VALUES ('Uzbek', 'uz');
INSERT INTO `languages` (`name`, `code`) VALUES ('Venda', 've');
INSERT INTO `languages` (`name`, `code`) VALUES ('Vietnamese', 'vi');
INSERT INTO `languages` (`name`, `code`) VALUES ('Volapük', 'vo');
INSERT INTO `languages` (`name`, `code`) VALUES ('Walloon', 'wa');
INSERT INTO `languages` (`name`, `code`) VALUES ('Wolof', 'wo');
INSERT INTO `languages` (`name`, `code`) VALUES ('Xhosa', 'xh');
INSERT INTO `languages` (`name`, `code`) VALUES ('Yiddish', 'yi');
INSERT INTO `languages` (`name`, `code`) VALUES ('Yoruba', 'yo');
INSERT INTO `languages` (`name`, `code`) VALUES ('Zhuang; Chuang', 'za');
INSERT INTO `languages` (`name`, `code`) VALUES ('Chinese', 'zh');
INSERT INTO `languages` (`name`, `code`) VALUES ('Zulu', 'zu');

/* languges flags */
UPDATE languages SET flag = 'de' WHERE code = 'de';
UPDATE languages SET flag = 'us' WHERE code = 'en';
UPDATE languages SET flag = 'fr' WHERE code = 'fr';
UPDATE languages SET flag = 'in' WHERE code = 'hi';
UPDATE languages SET flag = 'it' WHERE code = 'it';
UPDATE languages SET flag = 'jp' WHERE code = 'ja';
UPDATE languages SET flag = 'sa' WHERE code = 'ar';
UPDATE languages SET flag = 'es' WHERE code = 'es';
UPDATE languages SET flag = 'es' WHERE code = 'ca';
UPDATE languages SET flag = 'tr' WHERE code = 'tr';
UPDATE languages SET flag = 'ua' WHERE code = 'uk';
UPDATE languages SET flag = 'ru' WHERE code = 'ru';
UPDATE languages SET flag = 'pt' WHERE code = 'pt';
UPDATE languages SET flag = 'pl' WHERE code = 'pl';
UPDATE languages SET flag = 'cs' WHERE code = 'sr';
UPDATE languages SET flag = 'cn' WHERE code = 'zh';
UPDATE languages SET flag = 'by' WHERE code = 'be';
UPDATE languages SET flag = 'dk' WHERE code = 'da';
UPDATE languages SET flag = 'kr' WHERE code = 'ko';
UPDATE languages SET flag = 'nl' WHERE code = 'nl';
UPDATE languages SET flag = 'no' WHERE code = 'no';
UPDATE languages SET flag = 'ro' WHERE code = 'ro';
UPDATE languages SET flag = 'sl' WHERE code = 'sk';

-- +goose Down
-- SQL section 'Down' is executed when this migration is rolled back

